-- Generated gate probe: #print axioms on every name in proof-map §6 plus every
-- declaration in the frozen-signature probe (docs/signature-snapshot.md).
-- Deterministic; regenerate only when §6 or the snapshot gains names.
import EffectNatsSubstrate
open EffectNatsSubstrate

#print axioms afterOp
#print axioms all_sub_negatives
#print axioms all_sub_traces
#print axioms all_traces
#print axioms allTraces
#print axioms apply
#print axioms applyH
#print axioms applyH_erase
#print axioms applyH_lift
#print axioms applyOp
#print axioms applyPublish
#print axioms applyPull
#print axioms applyRegister
#print axioms applyUnsubscribe
#print axioms applyWith
#print axioms canonicalize
#print axioms capacityBounded
#print axioms cas_trace
#print axioms casTrace
#print axioms config_order_trace
#print axioms ConfigEq
#print axioms ConfigError
#print axioms configOrderTrace
#print axioms ConsumeOptions
#print axioms create_restarts
#print axioms createStream_conflict
#print axioms createStream_idempotent
#print axioms delete_ends
#print axioms delete_trace
#print axioms deleteTrace
#print axioms deliverOne
#print axioms dropOldest
#print axioms endOne
#print axioms entries_committed
#print axioms entrySequences
#print axioms erase
#print axioms erase_initialSubH
#print axioms Expect
#print axioms forSubject
#print axioms initialSub
#print axioms initialSubH
#print axioms insertStream
#print axioms isLastOfSubject
#print axioms isRollup
#print axioms JSError
#print axioms JSState
#print axioms keepLatest
#print axioms Label
#print axioms lagged_carries_last_observed
#print axioms lagged_iff
#print axioms lastForSubject
#print axioms lastMessage_absent
#print axioms lastMessage_max
#print axioms lastMessage_ok_iff
#print axioms lastSequenceFor
#print axioms lastSequenceFor_eq_zero_iff
#print axioms liveEntries
#print axioms lookupReg
#print axioms lookupStream
#print axioms lookupSub
#print axioms matchesAny
#print axioms memory_lastEnqueued_admissible
#print axioms newMessage
#print axioms newSubscriber
#print axioms Next
#print axioms NextH
#print axioms Observed
#print axioms Op
#print axioms op_visible_frame
#print axioms PayloadHash
#print axioms pending_le_capacity
#print axioms Policy
#print axioms positive_trace
#print axioms positiveTrace
#print axioms prune_trace
#print axioms pruneSubject
#print axioms pruneTrace
#print axioms publish_assigns
#print axioms publish_cas_iff
#print axioms publish_cas_mismatch
#print axioms publish_drops_oldest
#print axioms publish_ok_iff
#print axioms publish_other_subjects_unchanged
#print axioms publish_retains_latest
#print axioms publish_rollup_denied
#print axioms publish_rollup_view
#print axioms publish_unbound
#print axioms publish_visible
#print axioms publishBase
#print axioms pull_visible
#print axioms pullStep
#print axioms QueueStatus
#print axioms RawStreamConfig
#print axioms Reachable
#print axioms reachable_capacity
#print axioms reachable_inv
#print axioms reachable_positive
#print axioms reachable_sequences_strict
#print axioms ReachableSub
#print axioms reachableSub_core
#print axioms reachableSub_lift
#print axioms ReachableSubH
#print axioms RegInfo
#print axioms register_observed
#print axioms rejected_trace
#print axioms rejectedTrace
#print axioms removeStream
#print axioms replayBound
#print axioms replayObserved
#print axioms Ret
#print axioms rollup_denied_trace
#print axioms rollup_trace
#print axioms rollupDeniedTrace
#print axioms rollupTrace
#print axioms runTrace
#print axioms sa_accounting_trace
#print axioms sa_delete_trace
#print axioms sa_drain_trace
#print axioms sa_filters_trace
#print axioms sa_lag_trace
#print axioms sa_replay_trace
#print axioms sa_resume_trace
#print axioms sa_starts_trace
#print axioms saAccounting
#print axioms saDelete
#print axioms saDrain
#print axioms saFilters
#print axioms saLag
#print axioms saReplay
#print axioms saResume
#print axioms saStarts
#print axioms selectReplay
#print axioms selectReplay_lastPerSubject
#print axioms selectReplay_mem
#print axioms seqPositive
#print axioms StartPosition
#print axioms stateInv
#print axioms stateInv_reachable
#print axioms step
#print axioms StoredMessage
#print axioms StreamConfig
#print axioms streamInv
#print axioms StreamName
#print axioms StreamSeq
#print axioms StreamState
#print axioms sub_core_inv
#print axioms SubError
#print axioms SubId
#print axioms SubInv
#print axioms SubjectName
#print axioms Subscriber
#print axioms subscriberCount
#print axioms SubShape
#print axioms subShape_reachable
#print axioms SubState
#print axioms SubStateH
#print axioms Trace
#print axioms TraceStep
#print axioms updateStream
#print axioms updateSub
#print axioms validate
#print axioms validate_ok_sound
#print axioms validate_rejects_negative
#print axioms ViewCheck
#print axioms visible
#print axioms visible_global
#print axioms visible_sequences_strict
#print axioms w1_fails_drain
#print axioms w1_passes_replay
#print axioms w2_fails_lag
#print axioms w2_passes_drain
#print axioms sa_replay_lag_trace
#print axioms gated_in_outcomes
#print axioms w1_outside_outcomes
#print axioms w2_outside_outcomes
#print axioms all_rt_traces
#print axioms RtScenario.rt_before_trace
#print axioms RtScenario.rt_between_trace
#print axioms RtScenario.rt_after_trace
#print axioms RtScenario.rt_counterexample_trace
#print axioms RtScenario.rt_counterexample_admitted
#print axioms RtScenario.wrong_linearization_differs
#print axioms RtScenario.right_linearization_agrees
#print axioms RtScenario.rt_cases_admitted
#print axioms RtScenario.counterexample_inclusion_witness
#print axioms RtScenario.counterexample_wrong_witness
#print axioms takeAll_drains
#print axioms takeAll_closing
#print axioms fail_empty
#print axioms fail_nonempty
#print axioms exit_after_drain
#print axioms shutdown_clears
#print axioms size_eq_length
#print axioms offer_admits
#print axioms offer_refused
#print axioms lookupSub_updateSub_ne
#print axioms applyPull_other
#print axioms applyUnsubscribe_other
#print axioms applyOp_publish_each
#print axioms applyOp_delete_each
#print axioms applyOp_other_frame
#print axioms applyOp_error_frame
#print axioms pullStep_third_none
#print axioms pull_third_none
#print axioms agreeAt_refl
#print axioms agreeAt_symm
#print axioms agreeAt_trans
#print axioms applyPull_agreeAt
#print axioms apply_agreeAt
#print axioms observedOf_agreeAt
#print axioms allSubTraces_count
#print axioms allRtTraces_count
#print axioms sb1_witness
#print axioms sb3_witness
#print axioms a4complete_witness
#print axioms a4inclusion_witness
#print axioms abstractHistoryFrom_agreeAt
#print axioms abstractHistoryFrom_strip_pull
#print axioms DeliverLaws
#print axioms PullLaws
#print axioms deliverOne_laws
#print axioms pullStep_laws
#print axioms pullStepW1_laws
#print axioms deliverOneW2_laws
#print axioms w1_law_abiding_but_trace_excluded
#print axioms w2_law_abiding_but_trace_excluded
#print axioms afterOp_publish_sub_generic
#print axioms op_visible_frame_generic
#print axioms op_visible_frame_of_laws
#print axioms op_visible_frame_is_instance
#print axioms historiesFrom_contains
#print axioms Closed
#print axioms CorrAll
#print axioms CorrPost
#print axioms CorrPre
#print axioms FanFresh
#print axioms OwedOk
#print axioms Rel
#print axioms RelCore
#print axioms RelHist
#print axioms RelPre
#print axioms Scheduled
#print axioms corrSub
#print axioms failOpt
#print axioms isTargetOf
#print axioms owedOp
#print axioms pendingFail
#print axioms pendingOf
#print axioms pointPassed
#print axioms rtFail
#print axioms AgreeExcept
#print axioms CloseFree
#print axioms NoRegister
#print axioms NoUnsub
#print axioms RelStep
#print axioms TakeCase
#print axioms TargetStable
#print axioms a4_inclusion_of_rtInv
#print axioms a4_inclusion_pullOnly_of_rtInv
#print axioms a4_witness
#print axioms abstractHistoryFrom_append
#print axioms abstractHistoryFrom_congr
#print axioms abstractHistoryFrom_cons
#print axioms abstractHistoryFrom_frame
#print axioms abstractHistoryFrom_isSome
#print axioms abstractHistory_append
#print axioms abstractHistory_isSome
#print axioms admit_corr
#print axioms agreeAt_of_agreeExcept
#print axioms agreeAt_update
#print axioms agreeExcept_of_pull
#print axioms agreeExcept_of_unsubscribe
#print axioms agreeExcept_refl
#print axioms agreeExcept_update
#print axioms applyUnsubscribe_agreeAt
#print axioms apply_agreeExcept
#print axioms apply_agree_step
#print axioms apply_noRegister_frame
#print axioms closeA_corr
#print axioms closeB_corr
#print axioms closed_failOpt_of_closeStarted
#print axioms closed_failOpt_of_shutDown
#print axioms closed_rtFail
#print axioms consumerOnly_owedRest
#print axioms corrSub_observed
#print axioms corrSub_of_closed
#print axioms corrSub_of_erase
#print axioms corrSub_status
#print axioms corr_erase_of_target
#print axioms deleteStep_ret
#print axioms end_corr
#print axioms erase_queue_congr
#print axioms failOpt_chunks
#print axioms failOpt_closeStarted
#print axioms failOpt_lastEnqueued
#print axioms failOpt_ne_shutDown
#print axioms fail_buffer
#print axioms fail_ne_shutDown
#print axioms fail_of_ne_opened
#print axioms fail_status
#print axioms filter_length_cons
#print axioms flatten_single
#print axioms flatten_snoc
#print axioms isTargetOf_congr
#print axioms isTargetOf_delete_registered
#print axioms isTargetOf_of_unregistered
#print axioms isTargetOf_publish_registered
#print axioms labelSerial_append
#print axioms lookupRt_append
#print axioms lookupRt_isSome_of_keys
#print axioms lookupRt_none_of_fresh
#print axioms lookupRt_of_mem_pairwise
#print axioms lookupRt_updateRt_ne
#print axioms lookupRt_updateRt_self
#print axioms lookupRt_update_self
#print axioms lookupSub_isSome_of_keys
#print axioms lookupSub_none_of_keys
#print axioms lookupSub_updateSub_map
#print axioms lookup_lt_nextId
#print axioms mem_of_lookupRt
#print axioms noRegister_owed
#print axioms noUnsub_append
#print axioms noUnsub_of_append
#print axioms noUnsub_single
#print axioms not_closed_failOpt
#print axioms not_closed_of_registered
#print axioms not_closed_rtFail
#print axioms overflow_corr
#print axioms owedOp_ne_pull
#print axioms owedOp_ne_register
#print axioms owedOp_ne_unsubscribe
#print axioms owed_hist_frame
#print axioms owed_lookup
#print axioms park_corr
#print axioms pendingFail_congr
#print axioms pendingFail_of_decided_none
#print axioms pendingFail_of_not_passed
#print axioms pendingOf_eq
#print axioms pendingOf_of_decided_false
#print axioms pendingOf_of_decided_none
#print axioms pendingOf_of_delete
#print axioms pendingOf_of_not_passed
#print axioms pointPassed_check_admit
#print axioms pointPassed_check_overflow_ne
#print axioms pointPassed_check_overflow_self
#print axioms pointPassed_decided_false
#print axioms pointPassed_of_decided_none
#print axioms pointPassed_resolve_keep
#print axioms pointPassed_visit
#print axioms pullStep_closing
#print axioms pullStep_done
#print axioms pullStep_opened
#print axioms pullStep_targetStable
#print axioms pull_habs
#print axioms pull_hafter
#print axioms reachableRt_of_run
#print axioms reachableRt_run
#print axioms reachableRt_step
#print axioms relStep_of_consumer
#print axioms relStep_of_silent
#print axioms rel_consumer
#print axioms rel_initial
#print axioms rel_op_fanout
#print axioms rel_op_plain
#print axioms rel_resolve_keep
#print axioms rel_resolve_visit
#print axioms rel_run
#print axioms rel_silent
#print axioms rel_step
#print axioms rel_step_check
#print axioms rel_step_closeA
#print axioms rel_step_closeB
#print axioms rel_step_endFanOut
#print axioms rel_step_op
#print axioms rel_step_pull
#print axioms rel_step_register
#print axioms rel_step_resolve
#print axioms rel_step_wake
#print axioms rtHistory_eq
#print axioms rtRegister_cases
#print axioms rtSerial_append
#print axioms rtSubInv_of_lookup
#print axioms runLabels_agreeExcept
#print axioms runLabels_append
#print axioms runLabels_cons
#print axioms runLabels_consumer_frame
#print axioms runLabels_lookup_frame
#print axioms runLabels_noRegister_frame
#print axioms runLabels_single
#print axioms runLabels_snoc
#print axioms runRtSteps_append
#print axioms runRtSteps_cons
#print axioms status_ne_shutDown_of_opened
#print axioms subscriberCount_corr
#print axioms takeCase_fail
#print axioms take_corr
#print axioms take_corr_core
#print axioms unsub_habs
#print axioms unsub_hafter
#print axioms updateRt_keys
