-- Generated gate probe: #print axioms on every name in proof-map §6 plus every
-- declaration in the frozen-signature probe (docs/signature-snapshot.md).
-- Deterministic; regenerate only when §6 or the snapshot gains names.
import EffectNatsSubstrate
open EffectNatsSubstrate

#print axioms afterOp
#print axioms all_sub_negatives
#print axioms all_sub_traces
#print axioms all_traces
#print axioms allTraces
#print axioms apply
#print axioms applyH
#print axioms applyH_erase
#print axioms applyH_lift
#print axioms applyOp
#print axioms applyPublish
#print axioms applyPull
#print axioms applyRegister
#print axioms applyUnsubscribe
#print axioms applyWith
#print axioms canonicalize
#print axioms capacityBounded
#print axioms cas_trace
#print axioms casTrace
#print axioms config_order_trace
#print axioms ConfigEq
#print axioms ConfigError
#print axioms configOrderTrace
#print axioms ConsumeOptions
#print axioms create_restarts
#print axioms createStream_conflict
#print axioms createStream_idempotent
#print axioms delete_ends
#print axioms delete_trace
#print axioms deleteTrace
#print axioms deliverOne
#print axioms dropOldest
#print axioms endOne
#print axioms entries_committed
#print axioms entrySequences
#print axioms erase
#print axioms erase_initialSubH
#print axioms Expect
#print axioms forSubject
#print axioms initialSub
#print axioms initialSubH
#print axioms insertStream
#print axioms isLastOfSubject
#print axioms isRollup
#print axioms JSError
#print axioms JSState
#print axioms keepLatest
#print axioms Label
#print axioms lagged_carries_last_observed
#print axioms lagged_iff
#print axioms lastForSubject
#print axioms lastMessage_absent
#print axioms lastMessage_max
#print axioms lastMessage_ok_iff
#print axioms lastSequenceFor
#print axioms lastSequenceFor_eq_zero_iff
#print axioms liveEntries
#print axioms lookupReg
#print axioms lookupStream
#print axioms lookupSub
#print axioms matchesAny
#print axioms memory_lastEnqueued_admissible
#print axioms newMessage
#print axioms newSubscriber
#print axioms Next
#print axioms NextH
#print axioms Observed
#print axioms Op
#print axioms op_visible_frame
#print axioms PayloadHash
#print axioms pending_le_capacity
#print axioms Policy
#print axioms positive_trace
#print axioms positiveTrace
#print axioms prune_trace
#print axioms pruneSubject
#print axioms pruneTrace
#print axioms publish_assigns
#print axioms publish_cas_iff
#print axioms publish_cas_mismatch
#print axioms publish_drops_oldest
#print axioms publish_ok_iff
#print axioms publish_other_subjects_unchanged
#print axioms publish_retains_latest
#print axioms publish_rollup_denied
#print axioms publish_rollup_view
#print axioms publish_unbound
#print axioms publish_visible
#print axioms publishBase
#print axioms pull_visible
#print axioms pullStep
#print axioms QueueStatus
#print axioms RawStreamConfig
#print axioms Reachable
#print axioms reachable_capacity
#print axioms reachable_inv
#print axioms reachable_positive
#print axioms reachable_sequences_strict
#print axioms ReachableSub
#print axioms reachableSub_core
#print axioms reachableSub_lift
#print axioms ReachableSubH
#print axioms RegInfo
#print axioms register_observed
#print axioms rejected_trace
#print axioms rejectedTrace
#print axioms removeStream
#print axioms replayBound
#print axioms replayObserved
#print axioms Ret
#print axioms rollup_denied_trace
#print axioms rollup_trace
#print axioms rollupDeniedTrace
#print axioms rollupTrace
#print axioms runTrace
#print axioms sa_accounting_trace
#print axioms sa_delete_trace
#print axioms sa_drain_trace
#print axioms sa_filters_trace
#print axioms sa_lag_trace
#print axioms sa_replay_trace
#print axioms sa_resume_trace
#print axioms sa_starts_trace
#print axioms saAccounting
#print axioms saDelete
#print axioms saDrain
#print axioms saFilters
#print axioms saLag
#print axioms saReplay
#print axioms saResume
#print axioms saStarts
#print axioms selectReplay
#print axioms selectReplay_lastPerSubject
#print axioms selectReplay_mem
#print axioms seqPositive
#print axioms StartPosition
#print axioms stateInv
#print axioms stateInv_reachable
#print axioms step
#print axioms StoredMessage
#print axioms StreamConfig
#print axioms streamInv
#print axioms StreamName
#print axioms StreamSeq
#print axioms StreamState
#print axioms sub_core_inv
#print axioms SubError
#print axioms SubId
#print axioms SubInv
#print axioms SubjectName
#print axioms Subscriber
#print axioms subscriberCount
#print axioms SubShape
#print axioms subShape_reachable
#print axioms SubState
#print axioms SubStateH
#print axioms Trace
#print axioms TraceStep
#print axioms updateStream
#print axioms updateSub
#print axioms validate
#print axioms validate_ok_sound
#print axioms validate_rejects_negative
#print axioms ViewCheck
#print axioms visible
#print axioms visible_global
#print axioms visible_sequences_strict
#print axioms w1_fails_drain
#print axioms w1_passes_replay
#print axioms w2_fails_lag
#print axioms w2_passes_drain
#print axioms sa_replay_lag_trace
#print axioms gated_in_outcomes
#print axioms w1_outside_outcomes
#print axioms w2_outside_outcomes
#print axioms all_rt_traces
#print axioms RtScenario.rt_before_trace
#print axioms RtScenario.rt_between_trace
#print axioms RtScenario.rt_after_trace
#print axioms RtScenario.rt_counterexample_trace
#print axioms RtScenario.rt_counterexample_admitted
#print axioms RtScenario.wrong_linearization_differs
#print axioms RtScenario.right_linearization_agrees
#print axioms RtScenario.rt_cases_admitted
#print axioms RtScenario.counterexample_inclusion_witness
#print axioms RtScenario.counterexample_wrong_witness
